#!/bin/bash
touch 0-simply_match_school.rb 
touch 1-repetition_token_0.rb
touch 2-repetition_token_1.rb
touch 3-repetition_token_2.rb
touch 4-repetition_token_3.rb
touch 5-beginning_and_end.rb
touch 6-phone_number.rb
touch 7-OMG_WHY_ARE_YOU_SHOUTING.rb
touch 100-textme.rb
