#!/bin/bash

touch 0-what-is-my-pid
touch 1-list_your_processes
touch 2-show_your_bash_pid
touch 3-show_your_bash_pid_made_easy
touch 4-to_infinity_and_beyond
touch 5-dont_stop_me_now
touch 6-stop_me_if_you_can
touch 7-highlander
touch 8-beheaded_process
