#!/bin/bash
touch 0-RSA_public_key.pub
touch 1-for_best_school
touch 2-while_best_school
touch 3-until_best_school
touch 4-if_9_say_hi
touch 5-4_bad_luck_8_is_your_chance
touch 6-superstitious_numbers
touch 7-clock
touch 8-for_ls
touch 9-to_file_or_not_to_file
touch 10-fizzbuzz
